import { Residente } from "../../model/residente";

export const RESIDENTE_DATA: Residente[] = [
    {
      id: 1,
      esActivo: true,
      nombre: "RAQUEL",
      nombrePila: "RAQUEL",
      apellido: "BELLA",
      fechaIngreso: "2024-02-13",
      dniCuit: "46913810",
    },
    {
      id: 2,
      esActivo: true,
      nombre: "NELIDA",
      nombrePila: "NELIDA",
      apellido: "BOSIO",
      fechaIngreso: "2022-04-05",
      dniCuit: "23756669",
    },
    {
      id: 3,
      esActivo: true,
      nombre: "FELIPA",
      nombrePila: "FELIPA",
      apellido: "MAGARIÑOS",
      fechaIngreso: "2022-05-03",
      dniCuit: "22575562",
    },
    {
      id: 4,
      esActivo: true,
      nombre: "NIDIA",
      nombrePila: "NIDIA",
      apellido: "CAVERZASI",
      fechaIngreso: "2024-09-01",
      dniCuit: "90801586",
    },
    {
      id: 5,
      esActivo: true,
      nombre: "IMELDA",
      nombrePila: "IMELDA",
      apellido: "CHOCARELLO",
      fechaIngreso: "2019-11-20",
      dniCuit: "70291817",
    },/*
    {
      id: 6,
      esActivo: true,
      nombre: "DORIS",
      nombrePila: "DORIS",
      apellido: "DENASIO",
      fechaIngreso: "1956-04-22",
      dniCuit: "10872248",
    },
    {
      id: 7,
      esActivo: true,
      nombre: "ELVA",
      nombrePila: "ELVA",
      apellido: "DEPETRIS",
      fechaIngreso: "1932-06-18",
      dniCuit: "30868105",
    },
    {
      id: 8,
      esActivo: true,
      nombre: "IRMA",
      nombrePila: "IRMA",
      apellido: "FRANCESIA",
      fechaIngreso: "1924-08-01",
      dniCuit: "22448136",
    },
    {
      id: 9,
      esActivo: true,
      nombre: "IDID",
      nombrePila: "IDID",
      apellido: "GANDOLFO",
      fechaIngreso: "1936-02-07",
      dniCuit: "56164955",
    },
    {
      id: 10,
      esActivo: true,
      nombre: "ELSA",
      nombrePila: "ELSA",
      apellido: "GRIBAUDO",
      fechaIngreso: "1956-03-15",
      dniCuit: "15831819",
    },
    {
      id: 11,
      esActivo: true,
      nombre: "JUANA",
      nombrePila: "JUANA",
      apellido: "LLANOS",
      fechaIngreso: "1944-01-20",
      dniCuit: "26753883",
    },
    {
      id: 12,
      esActivo: true,
      nombre: "ELSA",
      nombrePila: "ELSA",
      apellido: "DANDREA",
      fechaIngreso: "1944-10-05",
      dniCuit: "49349722",
    },
    {
      id: 13,
      esActivo: true,
      nombre: "JAVIER",
      nombrePila: "JAVIER",
      apellido: "MACIAS",
      fechaIngreso: "1945-11-24",
      dniCuit: "35808537",
    },
    {
      id: 14,
      esActivo: true,
      nombre: "AIDE",
      nombrePila: "AIDE",
      apellido: "MARCHETTI",
      fechaIngreso: "1922-01-20",
      dniCuit: "98753260",
    },
    {
      id: 15,
      esActivo: true,
      nombre: "GRACIELA",
      nombrePila: "GRACIELA",
      apellido: "MARTINEZ",
      fechaIngreso: "1932-06-20",
      dniCuit: "70855700",
    },
    {
      id: 16,
      esActivo: true,
      nombre: "MARTA",
      nombrePila: "MARTA",
      apellido: "PEREYRA",
      fechaIngreso: "1936-08-09",
      dniCuit: "57683626",
    },
    {
      id: 17,
      esActivo: true,
      nombre: "INES",
      nombrePila: "INES",
      apellido: "ROJAS",
      fechaIngreso: "1947-04-29",
      dniCuit: "95225343",
    },
    {
      id: 18,
      esActivo: true,
      nombre: "OLGA",
      nombrePila: "OLGA",
      apellido: "ZARAZAGA",
      fechaIngreso: "1927-05-01",
      dniCuit: "72043515",
    },
    {
      id: 19,
      esActivo: true,
      nombre: "MARIA",
      nombrePila: "MARIA",
      apellido: "ARGUELLO",
      fechaIngreso: "1948-09-15",
      dniCuit: "84752529",
    },
    {
      id: 20,
      esActivo: true,
      nombre: "ROBERTO",
      nombrePila: "ROBERTO",
      apellido: "ARZUAGA",
      fechaIngreso: "1956-11-11",
      dniCuit: "14308421",
    },
    {
      id: 21,
      esActivo: true,
      nombre: "EVELINA",
      nombrePila: "EVELINA",
      apellido: "AUDO",
      fechaIngreso: "1937-12-29",
      dniCuit: "45935572",
    },
    {
      id: 22,
      esActivo: true,
      nombre: "DOMETILA",
      nombrePila: "DOMETILA",
      apellido: "BALLARDO",
      fechaIngreso: "1960-12-16",
      dniCuit: "86125617",
    },
    {
      id: 23,
      esActivo: true,
      nombre: "GRACIELA",
      nombrePila: "GRACIELA",
      apellido: "BOSSIO",
      fechaIngreso: "1949-05-26",
      dniCuit: "77005685",
    },
    {
      id: 24,
      esActivo: true,
      nombre: "ZULEMA",
      nombrePila: "ZULEMA",
      apellido: "ARTUSO",
      fechaIngreso: "1931-11-18",
      dniCuit: "28740864",
    },
    {
      id: 25,
      esActivo: true,
      nombre: "AURORA",
      nombrePila: "AURORA",
      apellido: "CAMPOS",
      fechaIngreso: "1960-04-09",
      dniCuit: "88320463",
    },
    {
      id: 26,
      esActivo: true,
      nombre: "MIGUEL",
      nombrePila: "MIGUEL",
      apellido: "CRAVERO",
      fechaIngreso: "1929-11-02",
      dniCuit: "28566572",
    },
    {
      id: 27,
      esActivo: true,
      nombre: "IRIS",
      nombrePila: "IRIS",
      apellido: "DIAZ",
      fechaIngreso: "1924-01-29",
      dniCuit: "16323852",
    },
    {
      id: 28,
      esActivo: true,
      nombre: "NELIDA",
      nombrePila: "NELIDA",
      apellido: "FORNERO",
      fechaIngreso: "1926-11-09",
      dniCuit: "94214382",
    },
    {
      id: 29,
      esActivo: true,
      nombre: "IRMA",
      nombrePila: "IRMA",
      apellido: "GENTY",
      fechaIngreso: "1946-10-02",
      dniCuit: "18526544",
    },
    {
      id: 30,
      esActivo: true,
      nombre: "ERMELINDA",
      nombrePila: "ERMELINDA",
      apellido: "GUZMAN",
      fechaIngreso: "1946-09-24",
      dniCuit: "72820592",
    },
    {
      id: 31,
      esActivo: true,
      nombre: "NORMA",
      nombrePila: "NORMA",
      apellido: "MINARI",
      fechaIngreso: "1944-10-25",
      dniCuit: "11540956",
    },
    {
      id: 32,
      esActivo: true,
      nombre: "ANA",
      nombrePila: "ANA",
      apellido: "MOLINERIS",
      fechaIngreso: "1954-06-23",
      dniCuit: "96028436",
    },
    {
      id: 33,
      esActivo: true,
      nombre: "JULIA",
      nombrePila: "JULIA",
      apellido: "JUAREZ",
      fechaIngreso: "1933-03-01",
      dniCuit: "68353204",
    },
    {
      id: 34,
      esActivo: true,
      nombre: "EVA",
      nombrePila: "EVA",
      apellido: "SANCHEZ",
      fechaIngreso: "1920-02-23",
      dniCuit: "45351479",
    },
    {
      id: 35,
      esActivo: true,
      nombre: "MARIA",
      nombrePila: "MARIA",
      apellido: "VIETTO",
      fechaIngreso: "1954-03-06",
      dniCuit: "33978249",
    },
    {
      id: 36,
      esActivo: true,
      nombre: "ESTER",
      nombrePila: "ESTER",
      apellido: "ZUYANI",
      fechaIngreso: "1957-10-02",
      dniCuit: "95758349",
    },*/
];